version: "3.1"

services:
  postgres:
    image: postgres:9.6.14
    ports:
      - "5420:5432"

    environment:
      - POSTGRES_DB=monitoring
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=111
